import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';

const NanumSquareNeoLt = localFont({
	src: '../assets/fonts/NanumSquareNeoTTF-aLt.woff',
	variable: '--font-nanum-square-neo-lt',
});
const NanumSquareNeoRg = localFont({
	src: '../assets/fonts/NanumSquareNeoTTF-bRg.woff',
	variable: '--font-nanum-square-neo-rg',
});
const NanumSquareNeoBd = localFont({
	src: '../assets/fonts/NanumSquareNeoTTF-cBd.woff',
	variable: '--font-nanum-square-neo-bd',
});
const NanumSquareNeoEb = localFont({
	src: '../assets/fonts/NanumSquareNeoTTF-dEb.woff',
	variable: '--font-nanum-square-neo-eb',
});
const NanumSquareNeoHv = localFont({
	src: '../assets/fonts/NanumSquareNeoTTF-eHv.woff',
	variable: '--font-nanum-square-neo-hv',
});

export const metadata: Metadata = {
	title: '이재환의 포트폴리오',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${NanumSquareNeoLt.variable} ${NanumSquareNeoRg.variable} ${NanumSquareNeoBd.variable} ${NanumSquareNeoEb.variable} ${NanumSquareNeoHv.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
