import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';

const SyneExtraBold = localFont({
	src: '../assets/fonts/Syne-ExtraBold.ttf',
	variable: '--font-syne-extra-bold',
});

const InconsolataMedium = localFont({
	src: '../assets/fonts/Inconsolata-Medium.ttf',
	variable: '--font-inconsolata-medium',
});

export const metadata: Metadata = {
	title: '이재환의 포트폴리오',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${SyneExtraBold.variable} ${InconsolataMedium.variable} antialiased bg-background`}>{children}</body>
		</html>
	);
}
